# Site settings
title: "Big Book of Brews"
author: "Saph, thebombzen, Desamir"
description:
  "A searchable D&D 5e spell list."
baseurl: "/Big_Book_of_Brews" # the subpath of your site, e.g. /blog/
url: "https://Big_Book_of_Brews.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/The-Onion-Grimoire/Big_Book_of_Brews/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"

collections:
  spells:
    output: true
  tags:
    output: true
